openapi: 3.0.3
info:
  title: Swagger For couponyo
  version: 0.0.1
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io

components:
  schemas:
    CouponSpecification:
      type: object
      properties:
        id:
          type: string
        applySubjects:
          type: string
        couponBenefits:
          type: string
        couponCondition:
          type: string
        couponName:
          type: string
        creator:
          type: string
        issuingEntity:
          type: string
        creationDate:
          type: string
        state:
          type: string
    CouponSpecificationsList:
      type: array
      items:
        $ref: "#components/schemas/CouponSpecification"
    CouponIssuance:
      type: object
      properties:
        id:
          type: string
        issuanceMethod:
          type: string
        couponName:
          type: string
        issuer:
          type: string
        issuedNumber:
          type: string
        issuancePeriod:
          type: string
        exprationDate:
          type: string
        state:
          type: string
        result:
          type: string
    CouponIssuanceList:
      type: array
      items:
        $ref: "#components/schemas/CouponIssuance"

paths:
  /coupon-specification/search:
    get:
      summary: Search Coupon Specification
      parameters:
        - in: query
          name: searchType
          schema:
            type: string
        - in: query
          name: searchTerm
          schema:
            type: string
        - in: query
          name: applySubject
          schema:
            type: string
        - in: query
          name: couponBenefit
          schema:
            type: string
        - in: query
          name: couponCondition
          schema:
            type: string
        - in: query
          name: couponName
          schema:
            type: string
        - in: query
          name: creator
          schema:
            type: string
        - in: query
          name: issuingEntity
          schema:
            type: string
        - in: query
          name: endTime
          required: true
          schema:
            type: string
        - in: query
          name: startTime
          required: true
          schema:
            type: string
      responses:
        "200":
          description: return coupon specifications list result
          content:
            application/json:
              schema:
                $ref: "#components/schemas/CouponSpecificationsList"
  /coupon-issuance/search:
    get:
      summary: Search Coupon Issuance
      parameters:
        - in: query
          name: searchType
          schema:
            type: string
        - in: query
          name: searchTerm
          schema:
            type: string
        - in: query
          name: searchDateType
          schema:
            type: string
        - in: query
          name: issuanceMethod
          schema:
            type: string
        - in: query
          name: endTime
          required: true
          schema:
            type: string
        - in: query
          name: startTime
          required: true
          schema:
            type: string
      responses:
        "200":
          description: return coupon issuance list result
          content:
            application/json:
              schema:
                $ref: "#components/schemas/CouponIssuanceList"
